openapi: 3.0.3
info:
  title: AMI API
  version: 1.0.0
  description: API de l'Application Mobile Interminitérielle
paths:
  /api/v1/fi/authorize/:
    get:
      operationId: api_v1_fi_authorize_retrieve
      tags:
      - api
      security:
      - {}
      responses:
        '200':
          description: No response body
  /api/v1/fi/logout/:
    get:
      operationId: api_v1_fi_logout_retrieve
      tags:
      - api
      security:
      - {}
      responses:
        '200':
          description: No response body
  /api/v1/fi/token/:
    post:
      operationId: api_v1_fi_token_create
      tags:
      - api
      security:
      - {}
      responses:
        '200':
          description: No response body
  /api/v1/fi/userinfo/:
    get:
      operationId: api_v1_fi_userinfo_retrieve
      tags:
      - api
      security:
      - {}
      responses:
        '200':
          description: No response body
  /api/v1/notifications:
    post:
      operationId: api_v1_notifications_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PartnerNotificationCreate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PartnerNotificationCreate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PartnerNotificationCreate'
        required: true
      security:
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotificationResponse'
          description: ''
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotificationResponse'
          description: ''
  /api/v1/partner/otv/public_key:
    get:
      operationId: api_v1_partner_otv_public_key_retrieve
      tags:
      - api
      security:
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PartnerPublicKeyResponse'
          description: ''
  /api/v1/partner/otv/url:
    get:
      operationId: api_v1_partner_otv_url_retrieve
      parameters:
      - in: query
        name: address_city
        schema:
          type: string
          minLength: 1
      - in: query
        name: address_name
        schema:
          type: string
          minLength: 1
      - in: query
        name: address_postcode
        schema:
          type: string
          minLength: 1
      - in: query
        name: email
        schema:
          type: string
          minLength: 1
      - in: query
        name: preferred_username
        schema:
          type: string
          minLength: 1
      tags:
      - api
      security:
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PartnerUrlResponse'
          description: ''
  /api/v1/users/agenda/items:
    get:
      operationId: api_v1_users_agenda_items_retrieve
      tags:
      - api
      security:
      - {}
      responses:
        '200':
          description: No response body
  /api/v1/users/follow-up/inventories:
    get:
      operationId: api_v1_users_follow_up_inventories_retrieve
      tags:
      - api
      security:
      - {}
      responses:
        '200':
          description: No response body
  /api/v1/users/notification/{notification_id}/read:
    patch:
      operationId: api_v1_users_notification_read_partial_update
      parameters:
      - in: path
        name: notification_id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedNotificationRead'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedNotificationRead'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedNotificationRead'
      security:
      - {}
      responses:
        '200':
          description: No response body
  /api/v1/users/notifications:
    get:
      operationId: api_v1_users_notifications_retrieve
      tags:
      - api
      security:
      - {}
      responses:
        '200':
          description: No response body
  /api/v1/users/registrations:
    get:
      operationId: api_v1_users_registrations_list
      tags:
      - api
      security:
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Registration'
          description: ''
    post:
      operationId: api_v1_users_registrations_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegistrationCreate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/RegistrationCreate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/RegistrationCreate'
      security:
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Registration'
          description: ''
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Registration'
          description: ''
  /api/v1/users/registrations/{registration_id}:
    delete:
      operationId: api_v1_users_registrations_destroy
      parameters:
      - in: path
        name: registration_id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - api
      security:
      - {}
      responses:
        '204':
          description: No response body
  /api/v1/users/scheduled-notifications:
    post:
      operationId: api_v1_users_scheduled_notifications_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScheduledNotificationCreate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ScheduledNotificationCreate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ScheduledNotificationCreate'
        required: true
      security:
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScheduledNotificationResponse'
          description: ''
    delete:
      operationId: api_v1_users_scheduled_notifications_destroy
      parameters:
      - in: query
        name: reference
        schema:
          type: string
          minLength: 1
        required: true
      tags:
      - api
      security:
      - {}
      responses:
        '204':
          description: No response body
  /check-auth:
    get:
      operationId: check_auth_retrieve
      tags:
      - check-auth
      security:
      - {}
      responses:
        '200':
          description: No response body
  /dev-utils/health/db-pool:
    get:
      operationId: dev_utils_health_db_pool_retrieve
      description: Returns database connection pool statistics for monitoring.
      tags:
      - dev-utils
      security:
      - {}
      responses:
        '200':
          description: No response body
  /dev-utils/recipient-fc-hash:
    get:
      operationId: dev_utils_recipient_fc_hash_retrieve
      parameters:
      - in: query
        name: birthcountry
        schema:
          type: string
          minLength: 1
        required: true
      - in: query
        name: birthdate
        schema:
          type: string
          minLength: 1
        required: true
      - in: query
        name: birthplace
        schema:
          type: string
          minLength: 1
      - in: query
        name: family_name
        schema:
          type: string
          minLength: 1
        required: true
      - in: query
        name: gender
        schema:
          type: string
          minLength: 1
        required: true
      - in: query
        name: given_name
        schema:
          type: string
          minLength: 1
        required: true
      tags:
      - dev-utils
      security:
      - {}
      responses:
        '200':
          description: No response body
  /dev-utils/review-apps:
    get:
      operationId: dev_utils_review_apps_retrieve
      description: 'Returns a list of tuples: (review app url, pull request title).'
      tags:
      - dev-utils
      security:
      - {}
      responses:
        '200':
          description: No response body
  /logout:
    post:
      operationId: logout_create
      tags:
      - logout
      security:
      - {}
      responses:
        '200':
          description: No response body
  /notification-key:
    get:
      operationId: notification_key_retrieve
      tags:
      - notification-key
      security:
      - {}
      responses:
        '200':
          description: No response body
  /schema:
    get:
      operationId: schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - ht
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - ug
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - schema
      security:
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /sector_identifier_url:
    get:
      operationId: sector_identifier_url_retrieve
      tags:
      - sector_identifier_url
      security:
      - {}
      responses:
        '200':
          description: No response body
components:
  schemas:
    ItemGenericStatusEnum:
      enum:
      - new
      - wip
      - closed
      type: string
      description: |-
        * `new` - new
        * `wip` - wip
        * `closed` - closed
    MobileAppSubscription:
      type: object
      properties:
        app_version:
          type: string
        device_id:
          type: string
        fcm_token:
          type: string
        model:
          type: string
        platform:
          type: string
      required:
      - app_version
      - device_id
      - fcm_token
      - model
      - platform
    MobileRegistrationCreate:
      type: object
      properties:
        subscription:
          $ref: '#/components/schemas/MobileAppSubscription'
      required:
      - subscription
    NotificationResponse:
      type: object
      properties:
        notification_id:
          type: string
          format: uuid
        notification_send_status:
          type: boolean
      required:
      - notification_id
      - notification_send_status
    PartnerNotificationCreate:
      type: object
      properties:
        recipient_fc_hash:
          type: string
          description: Hash de la concaténation des données pivot FC de l'usager destinataire,
            cf doc
        content_title:
          type: string
          description: Titre de la notification
        content_body:
          type: string
          description: Contenu de la notification
        content_private_body:
          type: string
          description: Contenu privé de la notification qui ne sera pas 'push'é
        content_icon:
          type: string
          description: Nom technique de l'icône à associer à la notification dans
            l'application AMI, à choisir dans [les icones du DSFR](https://www.systeme-de-design.gouv.fr/version-courante/fr/fondamentaux/icone).
        item_type:
          type: string
          description: 'Champ libre représentant le type de l''objet associé à la
            notification, par exemple : "OTV" dans le cas des démarches "Opération
            Tranquillité Vacances"'
        item_id:
          type: string
          description: Identifiant dans le référentiel partenaire de l'objet associé
            à la notification
        item_status_label:
          type: string
          description: 'objet associé à la notification, par exemple : "Brouillon"'
        item_generic_status:
          allOf:
          - $ref: '#/components/schemas/ItemGenericStatusEnum'
          description: |-
            Statut générique de l'objet associé à la notification pilotant des comportements spécifiques dans l'application AMI

            * `new` - new
            * `wip` - wip
            * `closed` - closed
        item_canal:
          type: string
          description: Canal source de l'objet associé à la notification (AMI, PSL,
            etc.) pour la mesure d'impact
        item_milestone_start_date:
          type: string
          format: date-time
          description: 'Date (au format ISO 8601) de début de la période correspondant
            à l''objet associé à la notification, ex : date de début de surveillance
            du logement dans le cadre d''une OTV'
        item_milestone_end_date:
          type: string
          format: date-time
          description: 'Date (au format ISO 8601) de fin de la période correspondant
            à l''objet associé à la notification, ex : date de fin de surveillance
            du logement dans le cadre d''une OTV'
        item_external_url:
          type: string
          description: Lien vers le portail du partenaire de l'objet associé à la
            notification
        send_date:
          type: string
          format: date-time
          description: Date (au format ISO 8601) d'émission de la notification côté
            partenaire
        try_push:
          type: boolean
          default: true
          description: Indique si le système doit essayer de déclencher une Notification
            Push sur les terminaux de l'usager
      required:
      - content_body
      - content_title
      - recipient_fc_hash
      - send_date
    PartnerPublicKeyResponse:
      type: object
      properties:
        public_key:
          type: string
      required:
      - public_key
    PartnerUrlResponse:
      type: object
      properties:
        partner_url:
          type: string
      required:
      - partner_url
    PatchedNotificationRead:
      type: object
      properties:
        read:
          type: boolean
    Registration:
      type: object
      properties:
        id:
          type: string
          format: uuid
        user_id:
          type: string
          format: uuid
        subscription:
          type: object
          additionalProperties: {}
        created_at:
          type: string
          format: date-time
      required:
      - created_at
      - id
      - subscription
      - user_id
    RegistrationCreate:
      oneOf:
      - $ref: '#/components/schemas/WebPushRegistrationCreate'
      - $ref: '#/components/schemas/MobileRegistrationCreate'
    ScheduledNotificationCreate:
      type: object
      properties:
        content_title:
          type: string
        content_body:
          type: string
        content_icon:
          type: string
        reference:
          type: string
        internal_url:
          type: string
        scheduled_at:
          type: string
          format: date-time
      required:
      - content_body
      - content_icon
      - content_title
      - reference
      - scheduled_at
    ScheduledNotificationResponse:
      type: object
      properties:
        scheduled_notification_id:
          type: string
          format: uuid
      required:
      - scheduled_notification_id
    WebPushKeys:
      type: object
      properties:
        auth:
          type: string
        p256dh:
          type: string
      required:
      - auth
      - p256dh
    WebPushRegistrationCreate:
      type: object
      properties:
        subscription:
          $ref: '#/components/schemas/WebPushSubscription'
      required:
      - subscription
    WebPushSubscription:
      type: object
      properties:
        endpoint:
          type: string
          format: uri
        keys:
          $ref: '#/components/schemas/WebPushKeys'
      required:
      - endpoint
      - keys
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
