name: workflow-e2e-main.yml
on:
  workflow_call:
    inputs:
      ref_name:
        type: string
        default: staging
      run_webapp:
        type: boolean
        default: false
      run_android:
        type: boolean
        default: false
      run_old_device:
        type: boolean
        default: true
      run_ios:
        type: boolean
        default: false
      source_repo:
        type: string
        required: true
      pr_number:
        type: number
        default: 0
    outputs:
      out_ref_name:
        description: "variable lue et modifiée pour poc"
        value: ${{ jobs.poc.outputs.out_ref_name }}
      out_webapp:
        description: "variable lue et modifiée pour poc"
        value: ${{ jobs.poc.outputs.out_webapp }}

#permissions:
#  contents: read
#  # actions:read pour interroger/télécharger les artifacts d'historique (propres à ce repo).
#  actions: read

jobs:
  poc:
    name: output to validate it works
    runs-on: ubuntu-latest
    steps:
      - name: dump variables
        id: dump
        # with: accès au script github ou un step uses
        # env: accès au shell pour un step run
        env:
          ref_name: ${{ inputs.ref_name }}
          run_webapp: ${{ inputs.run_webapp }}
          run_android: ${{ inputs.run_android }}
          run_old_device: ${{ inputs.run_old_device }}
          run_ios: ${{ inputs.run_ios }}
          source_repo: ${{ inputs.source_repo }}
          pr_number: ${{ inputs.pr_number }}
        run: |
          echo "ref_name is $ref_name and run_webapp is $run_webapp"
          env
          echo "out_ref_name=my_$ref_name" >> "$GITHUB_OUTPUT"
          echo "out_webapp=my_$run_webapp" >> "$GITHUB_OUTPUT"
    outputs:
      out_ref_name: ${{ steps.dump.outputs.out_ref_name }}
      out_webapp: ${{ steps.dump.outputs.out_webapp }}    

  webapp:
    if: ${{ inputs.run_webapp }}
    uses: ./.github/workflows/workflow-e2e-webapp.yml
    with:
      ref_name: ${{ inputs.ref_name }}
      run_webapp: ${{ inputs.run_webapp }}
    secrets: inherit

