name: workflow-e2e-ios.yml
on:
  workflow_call:
    inputs:
      ref_name:
        type: string
        default: staging
      checkout_ref:
        description: "ref (branche/tag/sha) d'ami-system-tests à checkout"
        type: string
        required: true

jobs:
  sample:
    runs-on: macos-latest
    steps:
      - run: echo hello world of iOS