name: workflow-e2e-webapp.yml
on:
  workflow_call:
    inputs:
      ref_name:
        type: string
        default: staging
      run_webapp:
        type: boolean
        default: false
      checkout_ref:
        type: string
        required: true

jobs:
  webapp-e2e:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ref_name }}
    env:
      REF_NAME: ${{ inputs.ref_name }}
      RUN_WEBAPP: ${{ inputs.run_webapp }}
      AMI_ENV: staging
      NOTIF_PARTNER_ID: ${{ secrets.NOTIF_PARTNER_ID }}
      NOTIF_PARTNER_SECRET: ${{ secrets.NOTIF_PARTNER_SECRET }}
      WEB_APP_ACCESS_KEYS: ${{ secrets.WEB_APP_ACCESS_KEYS }}
    defaults:
      run:
        working-directory: ami-system-tests
    steps:
      - uses: actions/checkout@v7
        with:
          repository: numerique-gouv/ami-system-tests
          ref: ${{ inputs.checkout_ref }}
          path: ami-system-tests
      - uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: ami-system-tests/package-lock.json
      - run: npm ci
      - uses: extractions/setup-just@v4
      - run: just test-webci-suite short
      - name: Exporter les résultats Allure
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-webapp
          path: allure-results-${{ github.run_id }}
          retention-days: 7
          if-no-files-found: warn
