appId: ${APP_ID}
tags:
  - android-only
---
- runFlow: ../../subflows/_launch.yaml
- runFlow: ../../subflows/franceconnect/open.yaml
- runFlow: ../../subflows/auth/login.yaml
- runFlow: ../../subflows/onboarding/dismiss.yaml
- runFlow: ../../subflows/settings/open.yaml

- assertVisible: "${output.settings_notif_label}"

- runFlow: ../../subflows/_back-android.yaml
- extendedWaitUntil:
    notVisible: "${output.settings_title}"
    timeout: 10000
